# Postgres database stack file
version: '3.1'

services:

  db:
    image: postgres:11.4
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgres-db:/var/lib/postgresql/data/
